export const dataColumns = [
  { Header: "Name", accessor: "name" },
  { Header: "Title", accessor: "title" },
  {
    Header: "Email",
    accessor: "email",
    minWidth: 100,
    width: 220,
    maxWidth: 220,
  },
  {
    Header: "Role",
    accessor: "role",
    minWidth: 60,
    width: 70,
    maxWidth: 100,
  },
  {
    Header: "",
    accessor: "actions",
    minWidth: 50,
    width: 70,
    maxWidth: 70,
    disableSortBy: true,
  },
];

export const actualData = [
  {
    name: "Lindsay Walton",
    title: "Front-end Developer",
    email: "lindsay.walton@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Courtney Henry",
    title: "Designer",
    email: "courtney.henry@example.com",
    role: "Admin",
    // actions: buttonActions,
  },
  {
    name: "Tom Cook",
    title: "Director, Product Development",
    email: "tom.cook@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Whitney Francis",
    title: "Copywriter",
    email: "whitney.francis@example.com",
    role: "Admin",
    // actions: buttonActions,
  },
  {
    name: "Leonard Krasner",
    title: "Senior Designer",
    email: "leonard.krasner@example.com",
    role: "Owner",
    // actions: buttonActions,
  },
  {
    name: "Floyd Miles",
    title: "Principal Designer",
    email: "floy.dmiles@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Emily Selman",
    title: "VP, User Experience",
    email: "emily.selman@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Kristin Watson",
    title: "VP, Human Resources",
    email: "kristin.watson@example.com",
    role: "Admin",
    // actions: buttonActions,
  },
  {
    name: "Emma Dorsey",
    title: "Senior Front-end Developer",
    email: "emma.dorsey@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Alicia Bell",
    title: "Junior Copywriter",
    email: "alicia.bell@example.com",
    role: "Admin",
    // actions: buttonActions,
  },
  {
    name: "Jenny Wilson",
    title: "Studio Artist",
    email: "jenny.wilson@example.com",
    role: "Owner",
    // actions: buttonActions,
  },
  {
    name: "Anna Roberts",
    title: "Partner, Creative",
    email: "anna.roberts@example.com",
    role: "Member",
    // actions: buttonActions,
  },
  {
    name: "Benjamin Russel",
    title: "Director, Print Operations",
    email: "benjamin.russel@example.com",
    role: "Member",
    // actions: buttonActions,
  },
];
